export enum AppEvents {
  SET_RECIPES,
  SET_CUR_RECIPE,
  SET_LOADING,
  SET_ERROR,
  SET_INGR_ARR,
  SET_INGR_ERR,
  SHOW_INGR_FIELDS,
  SET_STEPS_ARR,
  SET_STEPS_ERR,
  SHOW_STEPS_FIELDS,
  SET_SEND_LOADING,
  SET_SEND_ERR
}
